config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#home'
  get 'app' => "app#index"
  get 'pages' => "pages#index"

  get 'list-pages' => "pages#index", as: :list_pages
  get 'list-media' => "media#index", as: :list_media
  get 'list-book' => "books#index", as: :list_book
  get 'list-service' => "services#index", as: :list_service
  get 'list-corporate' => "corporates#index", as: :list_corporate
  get 'list-article' => "articles#index", as: :list_news
  get 'list-contact' => "contacts#index", as: :list_contact
  get 'phoenix-news' => "pages#ph_news", as: :ph_news
  get 'connect-with-us' => "pages#contact", as: :create_message

  get '/:id', to: 'pages#show', as: :pages_show

  resources :books,path:'publishing'
  resources :services,path:'creative-services'
  resources :corporates,path:'corporate-recognition'
  resources :articles,path:'phoenix-news'
  resources :authors
  resources :corporate_details
  resources :contacts
  resources :pages
  resources :users
  resources :media
  resources :book_previews
  resources :setups

  devise_for :users,
  path:'user',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }

  get ':category_name/:sub/:id', to: 'corporate_details#show', as: :dtl_sub_category

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  mount_uploader :image, ImageUploader
  mount_uploader :image_cover, ImageUploader

  Category = [ "marketing", "creative" ]

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :edit, :new]
  layout 'admin', only: [:index, :edit, :new]
  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
    prepare_meta_tags(
    title: @service.title,
    description: @service.meta_description,
    image: @service.image,
    twitter: {
      site_name: "Phoenix Communications | #{@service.title}" ,
      site: '@phoenix_IDN',
      creator: '@phoenix_IDN',
      card: 'summary',
      description:   @service.meta_description || ActionView::Base.full_sanitizer.sanitize(@service.content).truncate(250),
      title: @service.title,
      image: request.protocol + request.host_with_port + @service.image.url
    },
    og: {
      url: request.protocol + request.host_with_port+"/"+ @service.slug,
      site_name:  "Phoenix Communications | #{@service.title}" ,
      title: @service.title,
      image: request.protocol + request.host_with_port + @service.image.url,
      type: 'article',
      description:  @service.meta_description || ActionView::Base.full_sanitizer.sanitize(@service.content).truncate(250)
      })
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:title, :meta_description, :image,:image_cover, :main_content, :content, :slug, :category)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for @service, :html => { :class => "form-horizontal service" } do |f| %>

<% if @service.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @service.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="form-group">
          <%= f.label :title, :class => 'control-label' %>
          <%= f.text_field :title, :class => 'form-control' %>
          <%=f.error_span(:title) %>
        </div>

        <div class="form-group">
          <%= f.label :meta_description, :class => 'control-label' %>
          <%= f.text_area :meta_description, :class => 'form-control', rows: 4 %>
          <%=f.error_span(:meta_description) %>
        </div>

      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :image, :class => 'control-label' %>
            <% if @service.image.nil? || @service.image.blank? %>
              <%= f.file_field :image, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250' %>
            <% else %>
              <%= f.file_field :image, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250', 'data-default-file' => @service.image.url %>
            <% end %>
            <%=f.error_span(:image) %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :image_cover, :class => 'control-label' %>
            <% if @service.image_cover.nil? || @service.image_cover.blank? %>
              <%= f.file_field :image_cover, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250' %>
            <% else %>
              <%= f.file_field :image_cover, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250', 'data-default-file' => @service.image_cover.url %>
            <% end %>
            <%=f.error_span(:image_cover) %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <div class="form-group">
      <%= f.label :content, :class => 'control-label' %>
      <%= f.cktext_area :content, :class => 'form-control',:ckeditor => {:removePlugins => 'forms'} %>
      <%=f.error_span(:content) %>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <div class="form-group">
      <%= f.label :main_content, :class => 'control-label' %>
      <%= f.cktext_area :main_content, :class => 'form-control',:ckeditor => {:removePlugins => 'forms'} %>
      <%=f.error_span(:main_content) %>
    </div>
  </div>
</div>


<div class="card">
  <div class="card-body">
    <div class="form-group">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      services_path, :class => 'btn btn-default' %>
    </div>

  </div>
</div>

<% end %>

app/views/services/edit.html.erb
<%- model_class = Service -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= pages_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">

      <%= render :partial => 'form' %>

</div>

app/views/services/index.html.erb
<%- model_class = Service -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")), new_service_path, :class => 'btn btn-success mb-2' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:id) %></th>
                <th><%= model_class.human_attribute_name(:title) %></th>
                <th><%= model_class.human_attribute_name(:meta_description) %></th>
                <th><%= model_class.human_attribute_name(:category) %></th>
                <th><%= model_class.human_attribute_name(:created_at) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @services.each do |service| %>
              <tr>
                <td><%= link_to service.id, service_path(service) %></td>
                <td><%= service.title %></td>
                <td><%= service.meta_description %></td>
                <td><%= service.category %></td>
                <td><%=l service.created_at %></td>
                <td>
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  service_path(service), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_service_path(service), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  service_path(service),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  $(".table").dataTable();
});
</script>

app/views/services/new.html.erb
<%- model_class = Service -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= pages_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">

      <%= render :partial => 'form' %>

</div>

app/views/services/show.html.erb
<section id="intro" class="p-0">
  <div class="position-relative bg-intro" style="background:rgba(0, 0, 0, 0) url('<%= @service.image_cover %>') no-repeat fixed center center / cover;">
    <div class="d-absoulte h-100 w-100  d-flex align-items-end" style="background-color:rgba(6, 7, 8, 0.6)!important" >
      <div class="container mb-5">
        <div class="row">
          <div class="col-md-7">
            <h1 class="text-white"><%= @service.title %></h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="pb-0">
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-md-7">
        <%= @service.content.html_safe %>
      </div>
      <div class="col-md-4">
        <div class="sticky-top" style="top: 100px;z-index:0;">
          <h3>Others Services</h3>
          <hr>
          <ul style="list-style: decimal-leading-zero;">
            <% Service.where.not(id: @service.id).each do |x| %>
            <li><a href="<%= service_path(x.slug) %>"><%= x.title %></a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="main-content">
  <div class="container">
    <%= @service.main_content.html_safe %>
    <div class="text-center">
      <hr>
      <p>
        <strong class="text-classic" style="font-size: 25px">Contact us for more information</strong>   <br>
        E: <a href="mailto:creativeservices@phoenix.co.id"> <strong>creativeservices@phoenix.co.id</strong></a><br>
        T: +62 781 3212
      </p>
    </div>
  </div>
</section>