config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#home'
  get 'app' => "app#index"
  get 'pages' => "pages#index"

  get 'list-pages' => "pages#index", as: :list_pages
  get 'list-media' => "media#index", as: :list_media
  get 'list-book' => "books#index", as: :list_book
  get 'list-service' => "services#index", as: :list_service
  get 'list-corporate' => "corporates#index", as: :list_corporate
  get 'list-article' => "articles#index", as: :list_news
  get 'list-contact' => "contacts#index", as: :list_contact
  get 'phoenix-news' => "pages#ph_news", as: :ph_news
  get 'connect-with-us' => "pages#contact", as: :create_message

  get '/:id', to: 'pages#show', as: :pages_show

  resources :books,path:'publishing'
  resources :services,path:'creative-services'
  resources :corporates,path:'corporate-recognition'
  resources :articles,path:'phoenix-news'
  resources :authors
  resources :corporate_details
  resources :contacts
  resources :pages
  resources :users
  resources :media
  resources :book_previews
  resources :setups

  devise_for :users,
  path:'user',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }

  get ':category_name/:sub/:id', to: 'corporate_details#show', as: :dtl_sub_category

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  mount_uploader :image, ImageUploader
  belongs_to :author

  default_scope { order(publish: :desc) }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :edit, :new]
  layout 'admin', only: [:index, :edit, :new]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    prepare_meta_tags(
    title: @article.title,
    description: @article.meta_description,
    image: @article.image,
    twitter: {
      site_name: "Phoenix Communications| #{@article.title}" ,
      site: '@phoenix_IDN',
      creator: '@phoenix_IDN',
      card: 'summary',
      description:   @article.meta_description || ActionView::Base.full_sanitizer.sanitize(@article.content).truncate(250),
      title: @article.title,
      image: request.protocol + request.host_with_port + @article.image.url
    },
    og: {
      url: request.protocol + request.host_with_port+"/"+ @article.slug,
      site_name: "Phoenix Communications| #{@article.title}" ,
      title: @article.title,
      image: request.protocol + request.host_with_port + @article.image.url,
      type: 'article',
      description:  @article.meta_description || ActionView::Base.full_sanitizer.sanitize(@article.content).truncate(250)
      })
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :slug, :meta_description, :content, :image, :author_id, :publish)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => "form-horizontal article" } do |f| %>

<% if @article.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-8">
        <div class="form-group">
          <%= f.label :title, :class => 'control-label' %>
          <%= f.text_field :title, :class => 'form-control' %>
          <%=f.error_span(:title) %>
        </div>
        <div class="form-group">
          <%= f.label :meta_description, :class => 'control-label' %>
          <%= f.text_area :meta_description, :class => 'form-control', rows: 4 %>
          <%=f.error_span(:meta_description) %>
        </div>
        <div class="form-group">
          <%= f.label :author_id, :class => 'control-label' %>
          <%= f.select :author_id, Author.all.map {|s| [s.name, s.id ]},{:include_blank => '-Choose-'},:class=>"form-control w-100 select2"%>
          <%=f.error_span(:author_id) %>
        </div>
        <div class="form-group">
          <%= f.label :publish, :class => 'control-label' %>
          <%= f.date_field :publish, :class => 'form-control' %>
          <%=f.error_span(:publish) %>
        </div>
      </div>
      <div class="col-md-4">
        <%= f.label :image, :class => 'control-label' %>
        <% if @article.image.nil? || @article.image.blank? %>
        <%= f.file_field :image, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250' %>
        <% else %>
        <%= f.file_field :image, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250', 'data-default-file' => @article.image.url %>
        <% end %>
        <%=f.error_span(:image) %>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body" style="padding: 2rem !important;">

      <%= f.cktext_area :content, :class => 'form-control',:ckeditor => {:removePlugins => 'forms'} %>
      <%=f.error_span(:content) %>

  </div>
</div>


<div class="card text-center">
  <div class="card-body">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
    articles_path, :class => 'btn btn-default' %>
  </div>
</div>

<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Page -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")), new_article_path, :class => 'btn btn-success mb-2' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th class="text-center"><%= model_class.human_attribute_name(:id) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:title) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:author) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:created_at) %></th>
                <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @articles.each do |article| %>
              <tr>
                <td class="text-center"><%= link_to article.id, article_path(article) %></td>
                <td class="text-center"><%= article.title %></td>
                <td class="text-center"><%= article.author.name %></td>
                <td class="text-center"><%= article.created_at.strftime("%Y/%m/%d @%H:%M") rescue "-" %></td>
                <td class="text-center">
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  article_path(article), :class => 'btn btn-info btn-xs' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_article_path(article), :class => 'btn btn-warning btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  article_path(article),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $(".table").dataTable();
  });
</script>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<section id="intro" class="p-0">
  <div class="position-relative bg-intro-small" style="background:url('<%= article_cover_image(@article.author_id) %>') no-repeat fixed top center / cover">
    <div class="d-absoulte h-100 w-100  d-flex align-items-end" style="background-color:rgba(6, 7, 8, 0.6)!important" >
      <div class="container mb-5">
        <div class="row justify-content-center">
          <div class="col-md-12 text-center">
            <h1 class="text-white"><%= @article.title %></h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h4>Written by:</h4>
        <p><a href="<%= author_path(@article.author.slug) %>"><%= @article.author.name %></a></p>
        <hr>
        <h4>Posted on:</h4>
        <p><%= @article.publish.strftime("%e %B %Y") rescue "-" %></p>
        <hr>
        <h4>Share This Article</h4>
        <ul class="list-unstyled text-left d-flex">
          <li class="social-facebook mr-2">
            <a href="#"  class="fb-share" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=www.phoenix.co.id/<%= @article.slug %>','facebook-share-dialog','width=626,height=436');return false;">
              <img src="https://img.icons8.com/material-sharp/32/000000/facebook.png">
            </a>
          </li>
          <li class="social-twitter mr-2">
            <a target="_blank" href="https://twitter.com/intent/tweet?text=<%= @article.title %> , read more at: http://www.phoenix.co.id/<%= @article.slug %>">
              <img src="https://img.icons8.com/ios-glyphs/32/000000/twitter.png">
            </a>
          </li>
          <li class="social-wa mr-2">
            <a target="_blank" href="https://wa.me/?text=<%= u "#{@article.title} - http://nowjakarta.co.id/#{@article.slug}" %>">
              <img src="https://img.icons8.com/material/32/000000/whatsapp.png">
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-9">
        <div class="article">
          <%= @article.content.html_safe %>
        </div>
      </div>
    </div>
  </div>
</section>