config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#home'
  get 'app' => "app#index"
  get 'pages' => "pages#index"

  get 'list-pages' => "pages#index", as: :list_pages
  get 'list-media' => "media#index", as: :list_media
  get 'list-book' => "books#index", as: :list_book
  get 'list-service' => "services#index", as: :list_service
  get 'list-corporate' => "corporates#index", as: :list_corporate
  get 'list-article' => "articles#index", as: :list_news
  get 'list-contact' => "contacts#index", as: :list_contact
  get 'phoenix-news' => "pages#ph_news", as: :ph_news
  get 'connect-with-us' => "pages#contact", as: :create_message

  get '/:id', to: 'pages#show', as: :pages_show

  resources :books,path:'publishing'
  resources :services,path:'creative-services'
  resources :corporates,path:'corporate-recognition'
  resources :articles,path:'phoenix-news'
  resources :authors
  resources :corporate_details
  resources :contacts
  resources :pages
  resources :users
  resources :media
  resources :book_previews
  resources :setups

  devise_for :users,
  path:'user',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }

  get ':category_name/:sub/:id', to: 'corporate_details#show', as: :dtl_sub_category

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  mount_uploader :image, ImageUploader
  belongs_to :author

  default_scope { order(publish: :desc) }
end

app/models/author.rb
class Author < ApplicationRecord
  extend FriendlyId
  friendly_id :name

  has_many :articles
end

app/models/book.rb
class Book < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  mount_uploader :cover, ImageUploader
  mount_uploader :main_image, ImageUploader

  has_many :book_previews, dependent: :delete_all
  accepts_nested_attributes_for :book_previews, reject_if: :all_blank, allow_destroy: true


end

app/models/book_preview.rb
class BookPreview < ApplicationRecord
  belongs_to :book
  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ApplicationRecord

  Subject = [ "NOW! Jakarta and NOW! Bali", "Publishing", "Creative Services", "MVB and Say Yes to Less", "Management", "Career" ]

end

app/models/corporate.rb
class Corporate < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  mount_uploader :image_cover, ImageUploader
  mount_uploader :image, ImageUploader

  class << self
    def mvb
      Corporate.find("most-valued-business-mvb-indonesia")
    end

  end
end

app/models/medium.rb
class Medium < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  mount_uploader :image_cover, ImageUploader
  mount_uploader :image, ImageUploader

  class << self

    def nj
      Medium.find("now-jakarta")
    end

    def nb
      Medium.find("now-bali")
    end

    def brbca_nj
      Medium.find("now-jakarta-best-restaurant-bar-cafe-awards")
    end

    def brbca_nb
      Medium.find("now-bali-best-restaurant-bar-and-cafe-awards")
    end

    def njsc
      Medium.find("now-jakarta-schools-competition")
    end

    def nowstudy
      Medium.find("now-study")
    end

  end


end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  mount_uploader :image_thumbail, ImageUploader
  mount_uploader :image, ImageUploader

  validates :title, presence: true

  class << self

    def media
      Page.find("media")
    end

    def publishing
      Page.find("publishing")
    end

    def creative
      Page.find("creative-services")
    end

    def corporate
      Page.find("corporate-recognition")
    end

    def about
      Page.find("about-us")
    end

  end

end

app/models/publish.rb
class Publish < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  mount_uploader :cover, ImageUploader
  mount_uploader :image_intro, ImageUploader
end

app/models/service.rb
class Service < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  mount_uploader :image, ImageUploader
  mount_uploader :image_cover, ImageUploader

  Category = [ "marketing", "creative" ]

end

app/models/setup.rb
class Setup < ApplicationRecord
  mount_uploader :site_image, LogoUploader
  mount_uploader :site_favicon, IconUploader
  validates :site_name, presence: true
  validates :site_title, presence: true
  validates :site_url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId
  friendly_id :username
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :role, presence: true
  validates :email, presence: true

  mount_uploader :avatar, AvatarUploader

  ROLES = {root:'root',administrator:'administrator',author:'author', editor:'editor'}
  scope :root, -> {where(role: ROLES[:root])}
  scope :administrator, -> {where(role: ROLES[:administrator])}
  scope :author, -> {where(role: ROLES[:author])}
  scope :editor, -> {where(role: ROLES[:editor])}
  def is_root?
    self.role == ROLES[:root]
  end
  def is_administrator?
    self.role == ROLES[:administrator]
  end
  def is_author?
    self.role == ROLES[:author]
  end
  def is_editor?
    self.role == ROLES[:editor]
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :edit, :new]
  layout 'admin', only: [:index, :edit, :new]
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @articles = @author .articles
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :description, :skill)
    end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/_form.html.erb
<%= form_for @author, :html => { :class => "form-horizontal author" } do |f| %>

  <% if @author.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @author.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                authors_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/authors/edit.html.erb
<%- model_class = Author -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/authors/index.html.erb
<%- model_class = Page -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")), new_author_path, :class => 'btn btn-success mb-2' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th class="text-center"><%= model_class.human_attribute_name(:id) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:name) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:created_at) %></th>
                <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @authors.each do |author| %>
              <tr>
                <td class="text-center"><%= link_to author.id, author_path(author) %></td>
                <td class="text-center"><%= author.name %></td>
                <td class="text-center"><%= author.created_at.strftime("%Y/%m/%d @%H:%M") rescue "-" %></td>
                <td class="text-center">
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  author_path(author), :class => 'btn btn-info btn-xs' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_author_path(author), :class => 'btn btn-warning btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  author_path(author),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $(".table").dataTable();
  });
</script>

app/views/authors/new.html.erb
<%- model_class = Author -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/authors/show.html.erb
<section class="mt-5">
  <div class="container">
    <% @articles.each_with_index do |x, i| %>
      <% if i == 0 %>
      <div class="row">
        <div class="col-md-7">
          <div class="card border-0 mb-5">
            <img src="<%= x.image %>" alt="<%= x.title%>" class="w-100">
          </div>
        </div>
        <div class="col-md-5">
          <div class="card-body">
            <small class="text-danger"><%= x.publish.strftime("%e %B %Y") %></small>
            <h2><%= x.title%></h2>
            <p>
              <%= x.meta_description%>
            </p>
            <a href="<%= article_path(x.id) %>" class="btn btn-danger">
              Read more
            </a>
          </div>
        </div>

      </div>
      <hr>
    </div>
    <div class="container">
      <div class="row justify-content-between">
      <div class="col-md-7 mb-3">
        <% else %>
        <div class="card border-0 mb-5">
          <img src="<%= x.image %>" alt="<%= x.title%>" class="w-100">
          <div class="card-body">
            <small class="text-danger"><%= x.publish.strftime("%e %B %Y") %></small>
            <h2><%= x.title%></h2>
            <p>
              <%= x.meta_description%>
            </p>
            <a href="<%= article_path(x.id) %>" class="btn btn-danger">
              Read more
            </a>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
      <div class="col-md-3">
        <div class="mb-5" style="top:100px;">
          <h3>Category</h3>
          <ul style="list-style: decimal-leading-zero;">
            <% Author.where.not(id: @author.id).each do |x| %>
            <li><a href="<%= author_path(x.slug) %>"><%= x.name %></a></li>
            <% end %>
          </ul>
        </div>
        <div class="mb-5">
          <h3>NOW! Jakarta Latest Issue</h3>
          <img src="https://nowjakarta.co.id/uploads/category/cover/25/cover.jpg" alt="now jakarta" class="w-100 mb-3 shadow border-1">
          <a href="	http://emag.phoenix.co.id/redirections/now-jakarta-showcase" class="btn btn-danger w-100" target="_blank">
            Read NOW!
          </a>
        </div>
        <div class="mb-5">
          <h3>NOW! Bali Latest Issue</h3>
          <img src="https://nowbali.co.id/img/NB-COVER.jpg" alt="now jakarta" class="w-100 mb-3 shadow border-1">
          <a href="http://emag.phoenix.co.id/redirections/now-bali-business-card" class="btn btn-danger w-100" target="_blank">
            Read NOW!
          </a>
        </div>
      </div>
    </div>
  </div>
</section>