config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#home'
  get 'app' => "app#index"
  get 'pages' => "pages#index"

  get 'list-pages' => "pages#index", as: :list_pages
  get 'list-media' => "media#index", as: :list_media
  get 'list-book' => "books#index", as: :list_book
  get 'list-service' => "services#index", as: :list_service
  get 'list-corporate' => "corporates#index", as: :list_corporate
  get 'list-article' => "articles#index", as: :list_news
  get 'list-contact' => "contacts#index", as: :list_contact
  get 'phoenix-news' => "pages#ph_news", as: :ph_news
  get 'connect-with-us' => "pages#contact", as: :create_message

  get '/:id', to: 'pages#show', as: :pages_show

  resources :books,path:'publishing'
  resources :services,path:'creative-services'
  resources :corporates,path:'corporate-recognition'
  resources :articles,path:'phoenix-news'
  resources :authors
  resources :corporate_details
  resources :contacts
  resources :pages
  resources :users
  resources :media
  resources :book_previews
  resources :setups

  devise_for :users,
  path:'user',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }

  get ':category_name/:sub/:id', to: 'corporate_details#show', as: :dtl_sub_category

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/corporate.rb
class Corporate < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  mount_uploader :image_cover, ImageUploader
  mount_uploader :image, ImageUploader

  class << self
    def mvb
      Corporate.find("most-valued-business-mvb-indonesia")
    end

  end
end

app/controllers/corporates_controller.rb
class CorporatesController < ApplicationController
  before_action :set_corporate, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :edit, :new]
  layout 'admin', only: [:index, :edit, :new]
  # GET /corporates
  # GET /corporates.json
  def index
    @corporates = Corporate.all
  end

  # GET /corporates/1
  # GET /corporates/1.json
  def show
    prepare_meta_tags(
    title: @corporate.title,
    description: @corporate.meta_description,
    image: @corporate.image,
    twitter: {
      site_name: "Phoenix Communications | #{@corporate.title}" ,
      site: '@phoenix_IDN',
      creator: '@phoenix_IDN',
      card: 'summary',
      description:   @corporate.meta_description || ActionView::Base.full_sanitizer.sanitize(@corporate.content).truncate(250),
      title: @corporate.title,
      image: request.protocol + request.host_with_port + @corporate.image.url
    },
    og: {
      url: request.protocol + request.host_with_port+"/"+ @corporate.slug,
      site_name:  "Phoenix Communications | #{@corporate.title}" ,
      title: @corporate.title,
      image: request.protocol + request.host_with_port + @corporate.image.url,
      type: 'article',
      description:  @corporate.meta_description || ActionView::Base.full_sanitizer.sanitize(@corporate.content).truncate(250)
      })
  end

  # GET /corporates/new
  def new
    @corporate = Corporate.new
  end

  # GET /corporates/1/edit
  def edit
  end

  # POST /corporates
  # POST /corporates.json
  def create
    @corporate = Corporate.new(corporate_params)

    respond_to do |format|
      if @corporate.save
        format.html { redirect_to @corporate, notice: 'Corporate was successfully created.' }
        format.json { render :show, status: :created, location: @corporate }
      else
        format.html { render :new }
        format.json { render json: @corporate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /corporates/1
  # PATCH/PUT /corporates/1.json
  def update
    respond_to do |format|
      if @corporate.update(corporate_params)
        format.html { redirect_to @corporate, notice: 'Corporate was successfully updated.' }
        format.json { render :show, status: :ok, location: @corporate }
      else
        format.html { render :edit }
        format.json { render json: @corporate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corporates/1
  # DELETE /corporates/1.json
  def destroy
    @corporate.destroy
    respond_to do |format|
      format.html { redirect_to corporates_url, notice: 'Corporate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_corporate
      @corporate = Corporate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def corporate_params
      params.require(:corporate).permit(:title, :meta_description, :slug, :content, :image, :image_cover)
    end
end

app/helpers/corporates_helper.rb
module CorporatesHelper
end

app/views/corporates/_form.html.erb
<% if @corporate.errors.any? %>
<div class="alert alert-danger">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
  <h3 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <%= pluralize(@user.errors.count, "error") %> </h3>
  <p>prohibited this user from being saved:</p>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= form_for @corporate, :html => { :class => "form-horizontal corporate" } do |f| %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :title, :class => 'control-label' %>
              <%= f.text_field :title, :class => 'form-control', required: true %>
              <%=f.error_span(:title) %>
            </div>
          </div>
          <% unless @corporate.new_record? %>
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :slug, :class => 'control-label' %>
              <%= f.text_field :slug, :class => 'form-control', required: true %>
              <%=f.error_span(:slug) %>
            </div>
          </div>
          <% end %>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :meta_description, :class => 'control-label' %>
              <%= f.text_area :meta_description, :class => 'form-control' %>
              <%=f.error_span(:meta_description) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :image_thumbail, :class => 'control-label' %>
            <% if @corporate.image.nil? || @corporate.image.blank? %>
              <%= f.file_field :image, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250' %>
            <% else %>
              <%= f.file_field :image, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250', 'data-default-file' => @corporate.image.url %>
            <% end %>
            <%=f.error_span(:image) %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :image_cover, :class => 'control-label' %>
            <% if @corporate.image.nil? || @corporate.image.blank? %>
              <%= f.file_field :image_cover, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250' %>
            <% else %>
              <%= f.file_field :image_cover, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '250', 'data-default-file' => @corporate.image_cover.url %>
            <% end %>
            <%=f.error_span(:image_cover) %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <div class="form-group">
              <%= f.cktext_area :content, :class => 'form-control',:ckeditor => {:removePlugins => 'forms,save',:removeButtons => 'image,Flash,About' ,:startupMode => 'source'} %>
              <%=f.error_span(:content) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <div class="form-group">
      <%= f.submit nil, :class => 'btn btn-success' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),media_path, :class => 'btn btn-light' %>
    </div>
  </div>
</div>
<% end %>

app/views/corporates/edit.html.erb
<%- model_class = Corporate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/corporates/index.html.erb
<%- model_class = Corporate -%>
<div class="medium-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="medium-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")), new_corporate_path, :class => 'btn btn-success mb-2' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th class="text-center"><%= model_class.human_attribute_name(:id) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:title) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:created_at) %></th>
                <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @corporates.each do |corporate| %>
              <tr>
                <td class="text-center"><%= link_to corporate.id, corporate_path(corporate) %></td>
                <td class="text-center"><%= corporate.title %></td>
                <td class="text-center"><%= corporate.created_at.strftime("%Y/%m/%d @%H:%M") rescue "-" %></td>
                <td class="text-center">
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  corporate_path(corporate), :class => 'btn btn-info btn-xs' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_corporate_path(corporate), :class => 'btn btn-warning btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  corporate_path(corporate),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $(".table").dataTable();
  });
</script>

app/views/corporates/new.html.erb
<%- model_class = Corporate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/corporates/show.html.erb
<section id="intro" class="p-0">
  <div class="position-relative" style="background:rgba(0, 0, 0, 0) url('<%= @corporate.image_cover %>') no-repeat fixed top center / cover;height:75vh;">
    <div class="d-absoulte h-100 w-100  d-flex align-items-center" style="background-color:rgba(6, 7, 8, 0.3  )!important" >
      <div class="container ">
        <div class="caption  text-white w-75 ">
          <h1 class="text-white"><%= @corporate.title %></h1>
        </div>
      </div>
    </div>
  </div>
</section>

<%= @corporate.content.html_safe %>